name: Default Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: gcc compile
      run: make compile

    - name: valgrind memcheck
      run: |
        sudo apt-get install -y valgrind
        make memcheck
